In [1]:
import pandas as pd

df = pd.read_csv('NSMES1988.csv')
df.shape

(4406, 19)

In [30]:
df.describe()

,Unnamed: 0,visits,nvisits,ovisits,novisits,emergency,hospital,chronic,age,school,income
count,4406.000000,4406.000000,4406.000000,4406.000000,4406.000000,4406.000000,4406.000000,4406.000000,4406.000000,4406.000000,4406.000000
mean,2203.500000,5.774399,1.618021,0.750794,0.536087,0.263504,0.295960,1.541988,7.402406,10.290286,2.527132
std,1272.046972,6.759225,5.317056,3.652759,3.879506,0.703659,0.746398,1.349632,0.633405,3.738736,2.924648
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.600000,0.000000,-1.012500
25%,1102.250000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.900000,8.000000,0.912150
50%,2203.500000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,7.300000,11.000000,1.698150
75%,3304.750000,8.000000,1.000000,0.000000,0.000000,0.000000,0.000000,2.000000,7.800000,12.000000,3.172850
max,4406.000000,89.000000,104.000000,141.000000,155.000000,12.000000,8.000000,8.000000,10.900000,18.000000,54.835100

In [9]:
print(df.dtypes)

Unnamed: 0      int64
visits          int64
nvisits         int64
ovisits         int64
novisits        int64
emergency       int64
hospital        int64
health            str
chronic         int64
adl               str
region            str
age           float64
gender            str
married           str
school          int64
income        float64
employed          str
insurance         str
medicaid          str
dtype: object

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4406 entries, 0 to 4405
Data columns (total 19 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  4406 non-null   int64
 1   visits      4406 non-null   int64
 2   nvisits     4406 non-null   int64
 3   ovisits     4406 non-null   int64
 4   novisits    4406 non-null   int64
 5   emergency   4406 non-null   int64
 6   hospital    4406 non-null   int64
 7   health      4406 non-null   str
 8   chronic     4406 non-null   int64
 9   adl         4406 non-null   str
 10  region      4406 non-null   str
 11  age         4406 non-null   float64
 12  gender      4406 non-null   str
 13  married     4406 non-null   str
 14  school      4406 non-null   int64
 15  income      4406 non-null   float64
 16  employed    4406 non-null   str
 17  insurance   4406 non-null   str
 18  medicaid    4406 non-null   str
dtypes: float64(2), int64(9), str(8)
memory usage: 654.1 KB

In [17]:
 # Identify Categorical types in the data
cat_cols = df.select_dtypes(include=['object', 'category'])
print(cat_cols.columns.tolist())

['health', 'adl', 'region', 'gender', 'married', 'employed', 'insurance', 'medicaid']

C:\Users\UTL2397\AppData\Local\Temp\ipykernel_23052\3863621502.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include=['object', 'category'])

In [19]:
print(cat_cols.describe())

         health     adl region  gender married employed insurance medicaid
count      4406    4406   4406    4406    4406     4406      4406     4406
unique        3       2      4       2       2        2         2        2
top     average  normal  other  female     yes       no       yes       no
freq       3509    3507   1614    2628    2406     3951      3421     4004

In [24]:
categorical = df.select_dtypes(include=['object', 'category'])
print(categorical.columns)

Index(['health', 'adl', 'region', 'gender', 'married', 'employed', 'insurance',
       'medicaid'],
      dtype='str')

C:\Users\UTL2397\AppData\Local\Temp\ipykernel_23052\771823549.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical = df.select_dtypes(include=['object', 'category'])

In [25]:
numerical = df.select_dtypes(include=['int64', 'float64'])
print(numerical.columns)

Index(['Unnamed: 0', 'visits', 'nvisits', 'ovisits', 'novisits', 'emergency',
       'hospital', 'chronic', 'age', 'school', 'income'],
      dtype='str')

In [26]:
boolean = df.select_dtypes(include=['bool'])
print(boolean.columns)

Index([], dtype='str')

In [20]:
# Identify different types of data and report it
df.describe(include='all')

,Unnamed: 0,visits,nvisits,ovisits,novisits,emergency,hospital,health,chronic,adl,region,age,gender,married,school,income,employed,insurance,medicaid
count,4406.000000,4406.000000,4406.000000,4406.000000,4406.000000,4406.000000,4406.000000,4406,4406.000000,4406,4406,4406.000000,4406,4406,4406.000000,4406.000000,4406,4406,4406
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,2,4,NaN,2,2,NaN,NaN,2,2,2
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,average,NaN,normal,other,NaN,female,yes,NaN,NaN,no,yes,no
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3509,NaN,3507,1614,NaN,2628,2406,NaN,NaN,3951,3421,4004
mean,2203.500000,5.774399,1.618021,0.750794,0.536087,0.263504,0.295960,NaN,1.541988,NaN,NaN,7.402406,NaN,NaN,10.290286,2.527132,NaN,NaN,NaN
std,1272.046972,6.759225,5.317056,3.652759,3.879506,0.703659,0.746398,NaN,1.349632,NaN,NaN,0.633405,NaN,NaN,3.738736,2.924648,NaN,NaN,NaN
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000,NaN,NaN,6.600000,NaN,NaN,0.000000,-1.012500,NaN,NaN,NaN
25%,1102.250000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,1.000000,NaN,NaN,6.900000,NaN,NaN,8.000000,0.912150,NaN,NaN,NaN
50%,2203.500000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,1.000000,NaN,NaN,7.300000,NaN,NaN,11.000000,1.698150,NaN,NaN,NaN
75%,3304.750000,8.000000,1.000000,0.000000,0.000000,0.000000,0.000000,NaN,2.000000,NaN,NaN,7.800000,NaN,NaN,12.000000,3.172850,NaN,NaN,NaN
max,4406.000000,89.000000,104.000000,141.000000,155.000000,12.000000,8.000000,NaN,8.000000,NaN,NaN,10.900000,NaN,NaN,18.000000,54.835100,NaN,NaN,NaN

In [28]:
df.isnull().sum()

Unnamed: 0    0
visits        0
nvisits       0
ovisits       0
novisits      0
emergency     0
hospital      0
health        0
chronic       0
adl           0
region        0
age           0
gender        0
married       0
school        0
income        0
employed      0
insurance     0
medicaid      0
dtype: int64

In [29]:
df.nunique()

Unnamed: 0    4406
visits          60
nvisits         51
ovisits         37
novisits        35
emergency       11
hospital         9
health           3
chronic          9
adl              2
region           4
age             36
gender           2
married          2
school          19
income        3015
employed         2
insurance        2
medicaid         2
dtype: int64